[package]
name = "modular_translation_llm"
version = "0.1.0"
edition = "2024"

[dependencies]
c_ast.workspace = true
clang-ast = { version = "0.1.35", features = ["serde"] }
full_source.workspace = true
harvest_core = { workspace = true, features = ["llm-support"] }
identify_project_kind.workspace = true
llm = { default-features = false, features = ["ollama", "openai", "openrouter", "rustls-tls" ], version = "1.3.4" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = "1.48.0"
tracing = "0.1"

[lints]
workspace = true
