[package]
name = "auto_fix"
version = "0.1.0"
edition = "2024"

[dependencies]
harvest_core.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
thiserror.workspace = true
walkdir = "2"
chrono = "0.4"
fs_extra = "1.3"
rayon = "1.10"

[lints]
workspace = true
